
const themeToggle = document.getElementById("themeToggle");
const indicator=document.querySelector(".indicator");
const dark=document.querySelector(".dark");
const Tdark=document.querySelector(".Tdark");
const white=document.querySelector(".white");
const item1=document.querySelector(".item1");
const item2=document.querySelector(".item2");
const item3=document.querySelector(".item3");
const item4=document.querySelector(".item4");
const item5=document.querySelector(".item5");
const item6=document.querySelector(".item6");
const item7=document.querySelector(".item7");
const item8=document.querySelector(".item8");
const item9=document.querySelector(".item9");
const item10=document.querySelector(".item10");
const item11=document.querySelector(".item11");
const item12=document.querySelector(".item12");
const gitusername=document.querySelector(".gitusername");
const instausername=document.querySelector(".instausername");
const twitusername=document.querySelector(".twitusername");
const fbusername=document.querySelector(".fbusername");
const twitfollowers=document.querySelector(".twitfollowers");
const instafollowers=document.querySelector(".instafollowers");
const fbfollowers=document.querySelector(".fbfollowers");
const gitfollowers=document.querySelector(".gitfollowers");
const fbf=document.querySelector(".fbf");
const twitf=document.querySelector(".twitf");
const instaf=document.querySelector(".instaf");
const gitf=document.querySelector(".gitf");
const overview=document.querySelector(".overview");
const text5=document.querySelector(".text5");
const text6=document.querySelector(".text6");
const text7=document.querySelector(".text7");
const text8=document.querySelector(".text8");
const text9=document.querySelector(".text9");
const text10=document.querySelector(".text10");
const text11=document.querySelector(".text11");
const text12=document.querySelector(".text12");
const num5=document.querySelector(".num5");
const num6=document.querySelector(".num6");
const num7=document.querySelector(".num7");
const num8=document.querySelector(".num8");
const num9=document.querySelector(".num9");
const num10=document.querySelector(".num10");
const num11=document.querySelector(".num11");
const num12=document.querySelector(".num12");
// const followers=document.querySelectorAll("h4");
const body = document.body;

let isDarkTheme = false;

function toggleTheme() {
  isDarkTheme = !isDarkTheme;
  themeToggle.classList.toggle('active');
  if (isDarkTheme) {
    body.style.background = 'hsl(230, 17%, 14%)';
    themeToggle.style.background = 'hsl(140, 78%, 55%)';
    indicator.style.background = 'black';
    dark.style.color='hsl(230, 22%, 74%)';
    Tdark.style.color='hsl(230, 22%, 74%)';
    white.style.color='white';
    fbf.style.color='hsl(228, 12%, 44%)';
    twitf.style.color='hsl(228, 12%, 44%)';
    instaf.style.color='hsl(228, 12%, 44%)';
    gitf.style.color='hsl(228, 12%, 44%)';
    fbfollowers.style.color='white';
    twitfollowers.style.color='white';
    instafollowers.style.color='white';
    gitfollowers.style.color='white';
    gitusername.style.color='hsl(228, 34%, 66%)';
    instausername.style.color='hsl(228, 34%, 66%)';
    twitusername.style.color='hsl(228, 34%, 66%)';
    fbusername.style.color='hsl(228, 34%, 66%)';
    overview.style.color='white';
    text5.style.color='white';
    text6.style.color='white';
    text7.style.color='white';
    text8.style.color='white';
    text9.style.color='white';
    text10.style.color='white';
    text11.style.color='white';
    text12.style.color='white';
    num5.style.color='white';
    num6.style.color='white';
    num7.style.color='white';
    num8.style.color='white';
    num9.style.color='white';
    num10.style.color='white';
    num11.style.color='white';
    num12.style.color='white';
    item1.style.background = 'hsl(228, 28%, 20%)';
    item2.style.background = 'hsl(228, 28%, 20%)';
    item3.style.background = 'hsl(228, 28%, 20%)';
    item4.style.background = 'hsl(228, 28%, 20%)';
    item5.style.background = 'hsl(228, 28%, 20%)';
    item6.style.background = 'hsl(228, 28%, 20%)';
    item7.style.background = 'hsl(228, 28%, 20%)';
    item8.style.background = 'hsl(228, 28%, 20%)';
    item9.style.background = 'hsl(228, 28%, 20%)';
    item10.style.background = 'hsl(228, 28%, 20%)';
    item11.style.background = 'hsl(228, 28%, 20%)';
    item12.style.background = 'hsl(228, 28%, 20%)';
  } else {
    body.style.background = 'white';
    themeToggle.style.background = 'hsl(230, 22%, 74%)';
    indicator.style.background= 'white';
    white.style.color='hsl(230, 17%, 14%)';
    fbfollowers.style.color='hsl(230, 17%, 14%)';
    twitfollowers.style.color='hsl(230, 17%, 14%)';
    instafollowers.style.color='hsl(230, 17%, 14%)';
    gitfollowers.style.color='hsl(230, 17%, 14%)';
    gitusername.style.color='hsl(228, 12%, 44%)';
    instausername.style.color='hsl(228, 12%, 44%)';
    twitusername.style.color='hsl(228, 12%, 44%)';
    fbusername.style.color='hsl(228, 12%, 44%)';
    overview.style.color='hsl(228, 12%, 44%)';
    text5.style.color='hsl(228, 12%, 44%)';
    text6.style.color='hsl(228, 12%, 44%)';
    text7.style.color='hsl(228, 12%, 44%)';
    text8.style.color='hsl(228, 12%, 44%)';
    text9.style.color='hsl(228, 12%, 44%)';
    text10.style.color='hsl(228, 12%, 44%)';
    text11.style.color='hsl(228, 12%, 44%)';
    text12.style.color='hsl(228, 12%, 44%)';
    num5.style.color='hsl(230, 17%, 14%)';
    num6.style.color='hsl(230, 17%, 14%)';
    num7.style.color='hsl(230, 17%, 14%)';
    num8.style.color='hsl(230, 17%, 14%)';
    num9.style.color='hsl(230, 17%, 14%)';
    num10.style.color='hsl(230, 17%, 14%)';
    num11.style.color='hsl(230, 17%, 14%)';
    num12.style.color='hsl(230, 17%, 14%)';
    item1.style.background = 'hsl(227, 47%, 96%)';
    item2.style.background = 'hsl(227, 47%, 96%)';
    item3.style.background = 'hsl(227, 47%, 96%)';
    item4.style.background = 'hsl(227, 47%, 96%)';
    item5.style.background = 'hsl(227, 47%, 96%)';
    item6.style.background = 'hsl(227, 47%, 96%)';
    item7.style.background = 'hsl(227, 47%, 96%)';
    item8.style.background = 'hsl(227, 47%, 96%)';
    item9.style.background = 'hsl(227, 47%, 96%)';
    item10.style.background = 'hsl(227, 47%, 96%)';
    item11.style.background = 'hsl(227, 47%, 96%)';
    item12.style.background = 'hsl(227, 47%, 96%)';
  }
}

themeToggle.addEventListener('click', toggleTheme);




